// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABe_CTlC9fpHmIg9hdZRNqHIGl_XU7VXw',
    appId: '1:229630581257:web:3791ecc133b46ca6af76d8',
    messagingSenderId: '229630581257',
    projectId: 'ioi-firebase-ui-sample',
    authDomain: 'ioi-firebase-ui-sample.firebaseapp.com',
    storageBucket: 'ioi-firebase-ui-sample.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXBGuuCwteIa5vK9EB-cwu1xBEC7tS6p8',
    appId: '1:229630581257:android:a8468f2193e428a5af76d8',
    messagingSenderId: '229630581257',
    projectId: 'ioi-firebase-ui-sample',
    storageBucket: 'ioi-firebase-ui-sample.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0UPF3BGsuYNJxysOBdREcJ7hksVeoMa0',
    appId: '1:229630581257:ios:d6dc5827ac996a94af76d8',
    messagingSenderId: '229630581257',
    projectId: 'ioi-firebase-ui-sample',
    storageBucket: 'ioi-firebase-ui-sample.appspot.com',
    iosClientId: '229630581257-u91s978j6n9hlo9fsrikc8km74mpf538.apps.googleusercontent.com',
    iosBundleId: 'com.ioi.firebaseuisample',
  );
}
